language: node_js

node_js:
  - "lts/*"
  - "8"

go:
  - 1.9.x

env:
  - TEST_DIR=cothority
  - TEST_DIR=kyber

before_install:
  - go get -t ./...

script: cd external/js/$TEST_DIR && npm install && npm run test && npm run build

after_success:
  - npm run coveralls

notifications:
  email: false

matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get github.com/dedis/Coding || true

      before_install:
        - cd $TRAVIS_BUILD_DIR

      script:
        - make test

      notifications:
        email: false
