language: node_js

node_js:
  - "lts/*"
  - "8"

go:
  - 1.9.x

env:
  - TEST_DIR=cothority
  - TEST_DIR=kyber

#before_install:
#  - export GOPATH=$HOME/gopath
#  - export PATH=$HOME/gopath/bin:$PATH
#  - mkdir -p $HOME/gopath/src/github.com/dedis/cothority
#  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/dedis/cothority/
#  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/dedis/cothority
#  - cd $HOME/gopath/src/github.com/dedis/cothority
#  - echo $GOPATH
#  - eval "gimme 1.10"
#  - go get -t ./...
#  - cd external/js/

script: cd external/js/$TEST_DIR && npm install && npm run test && npm run build

after_success:
  - npm run coveralls

notifications:
  email: false

matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get github.com/dedis/Coding || true

      before_install:
        - cd $TRAVIS_BUILD_DIR

      script:
        - make test

      notifications:
        email: false
