language: node_js

install:
   - go get github.com/dedis/Coding || true
   - go get -t github.com/dedis/cothority/...

node_js:
  - "lts/*"
  - "8"

env:
  - TEST_DIR=cothority
#  - TEST_DIR=kyber

# Script will be run for each pair of (node_js X env) = 4 times
script:
  - cd external/js/$TEST_DIR && npm install && npm run test && npm run build
  - env
  - [ "$TEST_DIR" = "cothority" ] && cd ../../.. && make test 
  
after_success:
  - npm run coveralls

notifications:
  email: false



